
import { Book } from './types';

export const MOCK_BOOKS: Omit<Book, 'id'>[] = [
  {
    title: "A Comprehensive Guide to Fasting in Ramadan and the Day of 'Eid",
    author: "Abu Khadeejah",
    category: "Theology",
    year: 2024,
    description: "A comprehensive guide covering the rulings, manners, and virtues of fasting during the blessed month of Ramadan and the day of 'Eid.",
    historicalContext: "An essential modern reference for understanding the obligations and etiquettes of Ramadan fasting.",
    themes: ["Fasting", "Ramadan", "Worship"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2024/02/A-Comprehensive-Guide-To-Fasting-In-Ramadan-And-The-Day-Of-Eid-Abu-Khadeejah-Salafi-Publications-350x435.jpg",
    isbn: "9781902727677",
    pages: 200,
    language: "English",
    publisher: "Salafi Publications",
    price: "7.50",
    inStock: true
  },
  {
    title: "The Rights Of The Companions",
    author: "Ali Nasir al-Faqihi",
    category: "Theology",
    year: 2025,
    description: "An important treatise outlining the rights that the Companions of the Prophet hold in Islam and the obligation of loving and respecting them.",
    historicalContext: "Addresses one of the core tenets of Sunni Islamic belief regarding the Companions.",
    themes: ["Companions", "Aqeedah", "History"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/12/the-rights-of-the-companions-ali-nasir-faqihi-350x435.jpg",
    isbn: "9798350750829",
    pages: 180,
    language: "English",
    publisher: "Salafi Publications",
    price: "12.50",
    inStock: true
  },
  {
    title: "Ibn Taymiyyah on Divine Simplicity",
    author: "Ibn Taymiyyah",
    category: "Theology",
    year: 2025,
    description: "A detailed exploration of Ibn Taymiyyah's theological positions on the attributes of Allah and the concept of divine simplicity.",
    historicalContext: "Ibn Taymiyyah's works remain central to discussions on Islamic theology and creed.",
    themes: ["Aqeedah", "Theology", "Attributes"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/12/ibn-taymiyyah-on-divine-simplicity-350x435.jpg",
    isbn: "9781068309625",
    pages: 150,
    language: "English",
    publisher: "Salafi Publications",
    price: "10.00",
    inStock: true
  },
  {
    title: "The Easiest Explanation of Beneficial Speech in Establishing the Evidences of at-Tawhid",
    author: "Muhammad ibn Abdul-Wahhab",
    category: "Theology",
    year: 2025,
    description: "An accessible explanation of the foundational text 'Al-Qawl Al-Mufeed' which establishes the evidences for the Oneness of Allah.",
    historicalContext: "A key text in understanding Tawhid and the call of the great reformer Muhammad ibn Abdul-Wahhab.",
    themes: ["Tawhid", "Evidences", "Creed"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/12/evidence-at-tawheed-01__83653-350x435.jpg",
    isbn: "9780984660056",
    pages: 280,
    language: "English",
    publisher: "Salafi Publications",
    price: "16.95",
    inStock: true
  },
  {
    title: "Text, Translation and Commentary of Removal of the Doubts",
    author: "Muhammad ibn Abdul-Wahhab",
    category: "Theology",
    year: 2025,
    description: "A side-by-side Arabic text and English translation with commentary of the classical work 'Kashf ash-Shubuhaat' (Removal of the Doubts).",
    historicalContext: "One of the most important works addressing misconceptions about Tawhid.",
    themes: ["Tawhid", "Shirk", "Doubts"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/12/Removal-of-the-Doubts-Text-Translation-Commentary-350x435.jpg",
    isbn: "9798900306995",
    pages: 250,
    language: "English / Arabic",
    publisher: "Salafi Publications",
    price: "15.95",
    inStock: true
  },
  {
    title: "The History & Origins of the Kalam Theology of the Asharis and Maturidis",
    author: "Abu Iyaad",
    category: "History",
    year: 2025,
    description: "A scholarly examination of the historical origins and development of the Kalam theological methodology adopted by the Ashari and Maturidi schools.",
    historicalContext: "Traces the roots of speculative theology (Ilm al-Kalam) and its impact on Islamic thought.",
    themes: ["Kalam", "History", "Theology"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/12/The-History-Origins-of-the-Kalam-Theology-of-the-Asharis-and-Maturidis-350x435.jpg",
    isbn: "9798900306971",
    pages: 160,
    language: "English",
    publisher: "Salafi Publications",
    price: "8.50",
    inStock: true
  },
  {
    title: "The Four Principles Regarding Shirk",
    author: "Muhammad ibn Abdul-Wahhab",
    category: "Theology",
    year: 2025,
    description: "A concise treatise explaining the four fundamental principles by which the polytheism (Shirk) of the pre-Islamic Arabs can be understood.",
    historicalContext: "A foundational text for understanding the distinction between Tawhid and Shirk.",
    themes: ["Shirk", "Tawhid", "Principles"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/12/the-four-principles-regarding-shirk-muhammad-abdul-wahhab-350x435.jpg",
    isbn: "97818370922460",
    pages: 80,
    language: "English",
    publisher: "Salafi Publications",
    price: "4.95",
    inStock: true
  },
  {
    title: "Ease Granted by Allah in Explanation of the Evidences for the Conditions of La Ilaha Illa Allah",
    author: "Ubayd al-Jabiri",
    category: "Theology",
    year: 2025,
    description: "A detailed explanation of the conditions of the testimony of faith (Shahadah) and the evidences supporting each condition.",
    historicalContext: "Understanding the conditions of La Ilaha Illa Allah is essential for every Muslim.",
    themes: ["Shahadah", "Conditions", "Tawhid"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/12/ease-granted-by-allah-in-explanation-of-the-evidences-for-the-conditions-of-laa-ilaha-illa-allah-ubayd-jabiri-350x435.jpg",
    isbn: "9798901484661",
    pages: 180,
    language: "English",
    publisher: "Salafi Publications",
    price: "9.95",
    inStock: true
  },
  {
    title: "A Treatise in Refutation of the Shi'ah",
    author: "Muhammad ibn Abdul-Wahhab",
    category: "Theology",
    year: 2025,
    description: "A scholarly refutation addressing the beliefs and practices of the Shi'ah sect and their divergence from orthodox Islamic teachings.",
    historicalContext: "An important work in the tradition of defending Sunni orthodoxy.",
    themes: ["Refutation", "Sects", "Aqeedah"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/12/a-treatise-in-refutation-of-the-shiah-shaykh-islam-muhammad-abdul-wahhab-350x435.jpg",
    isbn: "1734814330",
    pages: 160,
    language: "English",
    publisher: "Salafi Publications",
    price: "9.00",
    inStock: true
  },
  {
    title: "A Radiant Masterpiece In Explanation Of The Poem Of Ibn Abee Daawud Al-Haa'iyah",
    author: "Ibn Abee Daawud",
    category: "Theology",
    year: 2025,
    description: "A comprehensive explanation of the famous poem Al-Haa'iyah which outlines the creed of Ahlus-Sunnah wal-Jama'ah.",
    historicalContext: "The Haa'iyah poem has been a cornerstone of Sunni creed education for centuries.",
    themes: ["Creed", "Poetry", "Sunnah"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/10/6021_PriceBreak_4782-350x435.jpg",
    isbn: "9781634438520",
    pages: 300,
    language: "English",
    publisher: "Salafi Publications",
    price: "16.00",
    inStock: true
  },
  {
    title: "The Nullifiers of Islam",
    author: "Muhammad ibn Abdul-Wahhab",
    category: "Theology",
    year: 2025,
    description: "A side-by-side Arabic and English text explaining the ten actions that nullify a person's Islam.",
    historicalContext: "One of the most studied short treatises in Islamic education worldwide.",
    themes: ["Nullifiers", "Islam", "Tawhid"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/07/the-nullifiers-of-islam-muhammad-abdul-wahhab-side-by-side-abu-iyaad-350x435.jpg",
    isbn: "9798899713521",
    pages: 60,
    language: "English / Arabic",
    publisher: "Salafi Publications",
    price: "3.50",
    inStock: true
  },
  {
    title: "The Six Principles",
    author: "Muhammad ibn Abdul-Wahhab",
    category: "Theology",
    year: 2025,
    description: "A side-by-side Arabic and English text of the six fundamental principles that every Muslim must understand.",
    historicalContext: "A concise but profound treatise on foundational Islamic principles.",
    themes: ["Principles", "Creed", "Foundation"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/07/the-six-principles-muhammad-abdul-wahhab-side-by-side-abu-iyaad-350x435.jpg",
    isbn: "9798899713538",
    pages: 50,
    language: "English / Arabic",
    publisher: "Salafi Publications",
    price: "3.75",
    inStock: true
  },
  {
    title: "The Wasitah Between Allah & The Creation",
    author: "Ibn Taymiyyah",
    category: "Theology",
    year: 2025,
    description: "A translation of Ibn Taymiyyah's work addressing the concept of intermediaries between Allah and His creation.",
    historicalContext: "Addresses one of the most critical theological issues in Islam regarding intercession and Tawhid.",
    themes: ["Intercession", "Tawhid", "Theology"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/07/the-wasitah-between-allah-and-the-creation-ibn-taymiyyah-350x435.jpg",
    isbn: "9798897665891",
    pages: 180,
    language: "English",
    publisher: "Salafi Publications",
    price: "9.95",
    inStock: true
  },
  {
    title: "The Creed of the Raziyayn | Workbook",
    author: "Salafi Publications",
    category: "Theology",
    year: 2025,
    description: "A workbook companion to the study of the Creed of the Raziyayn, designed for students to solidify their understanding of Islamic creed.",
    historicalContext: "The creed of Abu Zur'ah and Abu Hatim ar-Razi is a foundational text of Sunni orthodoxy.",
    themes: ["Workbook", "Creed", "Study"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/07/the-creed-of-the-raziyayn-workbook-salafi-publications-350x435.jpg",
    isbn: "9781902727875",
    pages: 100,
    language: "English",
    publisher: "Salafi Publications",
    price: "3.50",
    inStock: true
  },
  {
    title: "The Danger of Innovation in Light of The Perfection of The Shari'ah",
    author: "Shaykh Uthaymeen",
    category: "Theology",
    year: 2023,
    description: "An explanation of the dangers of religious innovation (Bid'ah) in light of the completeness and perfection of Islamic law.",
    historicalContext: "Innovation in religion (Bid'ah) is one of the most warned-against matters in Islam.",
    themes: ["Innovation", "Bidah", "Shariah"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2023/06/the-danger-of-innovation-in-light-of-the-perfect-sunnah-shaykh-uthaymeen-350x435.jpg",
    isbn: "9798897050895",
    pages: 120,
    language: "English",
    publisher: "Salafi Publications",
    price: "5.00",
    inStock: true
  },
  {
    title: "Explanation of the Four Fundamental Principles",
    author: "Saleh al-Fawzan",
    category: "Theology",
    year: 2025,
    description: "Shaykh Fawzan's explanation of Muhammad ibn Abdul-Wahhab's treatise on the four fundamental principles of Islamic monotheism.",
    historicalContext: "A widely-studied text in Islamic educational institutions around the world.",
    themes: ["Principles", "Tawhid", "Explanation"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2025/06/Explanation-of-the-Four-Fundamental-Principles-—-Fawzan-—-Salafipublications-–-Muhammad-Wahhab-600x600-1-350x435.jpg",
    isbn: "9781902727837",
    pages: 130,
    language: "English",
    publisher: "Salafi Publications",
    price: "4.95",
    inStock: true
  },
  {
    title: "Beneficial Speech in Establishing the Evidences of At-Tawheed",
    author: "Muhammad Al-Wasaabee",
    category: "Theology",
    year: 2022,
    description: "An important work establishing the proofs and evidences for Tawhid (Islamic monotheism) from the Quran and Sunnah.",
    historicalContext: "A modern classic in the field of Tawhid education.",
    themes: ["Tawhid", "Evidences", "Quran"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2022/01/Beneficial-Speech-in-Establishing-the-Evidences-of-At-Tawheed-—-Shaikh-Muhammad-Al-Wasaabee-—-9781902727707-—-Salafi-Publications-350x435.jpg",
    isbn: "9781902727745",
    pages: 200,
    language: "English",
    publisher: "Salafi Publications",
    price: "8.50",
    inStock: true
  },
  {
    title: "The Explanation of Al-Ha'iyyah",
    author: "Saleh al-Fawzan",
    category: "Theology",
    year: 2017,
    description: "Dr. Salih al-Fawzan's detailed explanation of the poem Al-Ha'iyyah, covering the fundamental beliefs of Ahlus-Sunnah.",
    historicalContext: "A scholarly commentary on one of the most important poems on Islamic creed.",
    themes: ["Creed", "Explanation", "Poetry"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2017/05/the-explanation-of-al-haiyyah-dr-salih-al-fawzan-350x435.jpg",
    isbn: "9780984660032",
    pages: 350,
    language: "English",
    publisher: "Salafi Publications",
    price: "17.95",
    inStock: true
  },
  {
    title: "The Book Of Worship: Its Meaning, Conditions, Characteristics, and Perfection",
    author: "Abu Iyaad",
    category: "Theology",
    year: 2023,
    description: "A detailed exploration of the concept of worship in Islam — its meaning, necessary conditions, characteristics, and how to perfect it.",
    historicalContext: "Understanding worship is central to the practice of Islam.",
    themes: ["Worship", "Ibadah", "Conditions"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2023/06/the-book-of-worship-its-meaning-conditions-characteristics-and-perfection-abu-iyaad-350x435.jpg",
    isbn: "9798897048151",
    pages: 140,
    language: "English",
    publisher: "Salafi Publications",
    price: "5.50",
    inStock: true
  },
  {
    title: "The Meaning of Islam",
    author: "Abu Iyaad",
    category: "Theology",
    year: 2023,
    description: "A brief yet comprehensive explanation of the most important principles and teachings of Islam, suitable as a guide for new Muslims and non-Muslims.",
    historicalContext: "A modern introduction to Islam grounded in authentic scholarship.",
    themes: ["Introduction", "Islam", "Principles"],
    coverImage: "https://salafibookstore.com/wp-content/uploads/2023/06/the-meaning-of-islam-4rd-edition-brief-guide-important-principles-teaching-islam-abu-iyaad-350x435.jpg",
    isbn: "9781640073807",
    pages: 160,
    language: "English",
    publisher: "Salafi Publications",
    price: "5.95",
    inStock: true
  }
];

export const CATEGORIES: string[] = ['All', 'Theology', 'History'];
